apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
spec:
  selector:
    app: tic-tac-toe
  ports:
  - protocol: TCP
    port: 8501          # porta do Service
    targetPort: 8501     # porta do container (Streamlit)
    # nodePort: 30080
  type: LoadBalancer # ou NodePort